#!/bin/sh
####################################################################################################
#
# FILENAME:     ##FILENAME## (NOTE: This should be executable, so do not add the .sh file extention)
#
# PURPOSE:      ##ADD_PURPOSE_HERE##
#
# DESCRIPTION:  ##ADD_DESCRIPTIION_HERE##
#
# INSTRUCTIONS: Execute the following command relative to your project's root directory:  
#               ./dev-tools/##FILENAME##
#
# RELATED DOCS: TODO: ?????
#               └─ https://???.???.com
#
#               TODO: ?????
#               ├─ https://www.????.com
#               └─ https://www.????.com
#
####################################################################################################
#
##
###
#### LOAD SHARED FUNCTIONS LIBRARY #################################################################
###
##
#
if [ ! -r `dirname $0`/lib/shared-functions.sh ]; then
  echo "\nFATAL ERROR: `tput sgr0``tput setaf 1`Could not load dev-tools/lib/shared-functions.sh.  File not found.\n"
  exit 1
fi
source `dirname $0`/lib/shared-functions.sh
#
##
###
#### CONFIRM SCRIPT EXECUTION ######################################################################
###
##
#
confirmScriptExecution "Do you want to setup Partner-specific Data in the Demo Org?"
#
##
###
#### CREATE LOCAL VARIABLES ########################################################################
###
##
#
TARGET_DEMO_ORG_ALIAS=$SALESFORCE_DEMO_ORG_ALIAS
PROJECT_ROOT=$SALESFORCE_PROJECT_ROOT
#
##
###
#### INSTALL PARTNER PACKAGES ######################################################################
###
##
#
# Install the MAIN Partner Package.
#installPackage $DEMO_PACKAGE_VERSION_ID_01 \
#               "MAIN Partner Package" \
#               "Install the Main Partner Package into the $TARGET_DEMO_ORG_ALIAS org"

# Install the SECOND Partner Package. (uncomment if needed)
#installPackage $DEMO_PACKAGE_VERSION_ID_02 \
#               "SECOND Partner Package" \
#               "Install the Second Partner Package into the $TARGET_DEMO_ORG_ALIAS org"

# Install the THIRD Partner Package. (uncomment if needed)
#installPackage $DEMO_PACKAGE_VERSION_ID_03 \
#               "THIRD Partner Package" \
#               "Install the Third Partner Package into the $TARGET_DEMO_ORG_ALIAS org"

# Install the FOURTH Partner Package. (uncomment if needed)
#installPackage $DEMO_PACKAGE_VERSION_ID_04 \
#               "FOURTH Partner Package" \
#               "Install the Fourth Partner Package into the $TARGET_DEMO_ORG_ALIAS org"

# Install the FIFTH Partner Package. (uncomment if needed)
#installPackage $DEMO_PACKAGE_VERSION_ID_05 \
#               "FIFTH Partner Package" \
#               "Install the Fifth Partner Package into the $TARGET_DEMO_ORG_ALIAS org"
#
##
###
#### ASSIGN PERMISSION SETS ########################################################################
###
##
#
# Assign packaged permission sets to specific users (ADMIN, PRIMARY, and/or SECONDARY).
assignPermset "FinServ__Advisor" \
              "$DEMO_ADMIN_USER,
               $DEMO_PRIMARY_USER,
               $DEMO_SECONDARY_USER"

# Repeat permission set assignments as many times as necessary using the following template:
#assignPermset "NameSpace__PermSetApiName" \
#              "$DEMO_ADMIN_USER,
#               $DEMO_PRIMARY_USER,
#               $DEMO_SECONDARY_USER"

#
##
###
#### POST-INSTALL MDAPI DEPLOYMENTS ################################################################
###
##
#

# Deploy Org Config Metadata
#deployMdapiSource "org-config"

# Deploy App Config Metadata
deployMdapiSource "app-config"

# Deploy Data Config Metadata
deployMdapiSource "data-config"

#
##
###
#### IMPORT/CREATE DEMO DATA #######################################################################
###
##
#



#
##
###
#### ECHO CLOSING MESSAGE ##########################################################################
###
##
#
echoScriptCompleteMsg \
"Script completed successfully."
exit 0

##END##