

export enum INTENT {
  BUILD_SCRATCH_ORG = 'BUILD_SCRATCH_ORG',
  DEPLOY_DEMO       = 'DEPLOY_DEMO',  
  HEALTH_CHECK      = 'HEALTH_CHECK',
  NOT_SPECIFIED     = 'NOT_SPECIFIED',
  REPAIR_PROJECT    = 'REPAIR_PROJECT',
  VALIDATE_DEMO     = 'VALIDATE_DEMO'
}

export enum ERROR_TYPE {
  CLI_ERROR       = 'CLI_ERROR',
  INTERNAL_ERROR  = 'INTERNAL_ERROR',
  FALCON_ERROR    = 'FALCON_ERROR',
  UNPARSED_ERROR  = 'UNPARSED_ERROR'
}